### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by icpantsparti2** [arkenfox/gui#3]
I added some initial values taken from TZP as you can see: https://arkenfox.github.io/gui

@Thorin-Oakenpants over to you for your choices

EDIT: see `/* arkenfox theme */` section in [userjs-tool-themes.css](https://github.com/arkenfox/gui/blob/main/css/userjs-tool-themes.css)

<details><summary>color values from TZP code</summary>

```css
// mm color: 418986: FF41+ RFP
let match = true, r = "", c = "#ff4f4f"
if (match) {c = "#8cdc8c"}
context.fillStyle = "#f60";
context.fillStyle = "#069";
context.fillStyle = "rgba(102, 204, 0, 0.7)";
context.fillStyle = "rgb(255,0,255)"
context.fillStyle = "rgb(0,255,255)"
context.fillStyle = "rgb(255,255,0)"
context.fillStyle = "#000"
ctx.fillStyle = "rgba("+ (x*y) +","+ (x*16) +","+ (y*16) +",255)"
ctx2.fillStyle = "rgba(255,255,255,255)"
element.style.backgroundColor = "rgba(1,2,3,0.5)"
zhide = "#161b22",
zshow = "#b3b3b3",
<div id="test95a" style="width: min-content; hyphens: auto; border: 1px solid red">2020-1</div>
<div id="test95b" style="width: min-content; hyphens: auto; border: 1px solid red">2020-12020-1</div>
--test1: #dc8c8c;
--test2: #dca78c;
--test3: #dcc18c;
--test4: #dcdc8c;
--test5: #c1dc8c;
--test6: #a7dc8c;
--test7: #8cdc8c;
--test8: #8cdca7;
--test9: #8cdcc1;
--test10: #8cdcdc;
--test11: #8cc1dc;
--test12: #8ca7dc;
--test13: #8c8cdc;
--test14: #a78cdc;
--test15: #c18cdc;
--test16: #dc8cdc;
--test17: #dc8cc1;
--test18: #dc8ca7;
--test99: #808080;
body {background-color: #161b22; color: #b3b3b3;}
h2 {color: white; font-size: 14px; text-align: center; margin-top: inherit;}
background: #41424d !important;
border: 1px solid rgba(255, 255, 255, .1);
background-color: rgba(255, 79, 79, 0.6) !important;
color: white;
background-color: rgba(140, 220, 193, 0.4) !important; /* test9 */
a {color: black; text-decoration: none;}
a.blue {color: #8ca7dc; text-decoration: none;}
a.return {color: #8ca7dc; text-decoration: none; font-size: 14px; line-height: 1.2em}
.no_color {color: #b3b3b3;}
.faint {color: #606060;} /* #888888 darker off white */
.good {color: #8cdc8c;} /* test7 */
.bad {color: #ff4f4f;}
.neutral {color: #dcdc8c;} /* test4 */
.orange {color: #dca78c;} /* test2 */
.btn {background-color: #161b22;
.btn0 {border-color: #b3b3b3; color: #b3b3b3;}
.btnbad, .sbad {border-color: #ff4f4f; color: #ff4f4f;}
.icon {font-size: 10px; font-weight: bold; color: #b3b3b3; cursor: default;}
.ttip {position: relative; display: inline-block; border-bottom: 1px dotted black; color: white;}
visibility: hidden; width: 150px; background-color: #b3b3b3; color: black; text-align: center;
visibility: hidden; width: 210px; background-color: #b3b3b3; color: black; text-align: center;
visibility: hidden; width: 250px; background-color: #b3b3b3; color: black; text-align: center;
border-style: solid; border-color: transparent #b3b3b3 transparent transparent;}
tbody:before {content: "-"; display: block; line-height: 1em; color: transparent;}
th {color: black; font-weight: bold; font-size: 16px; padding: 3px 0;}
#tb1 th {background-color: #f07878;}
#tb2 th {background-color: #f0a078;}
#tb3 th {background-color: #f0c878;}
#tb4 th {background-color: #f0f078;}
#tb5 th {background-color: #c8f078;}
#tb6 th {background-color: #a0f078;}
#tb7 th {background-color: #78f078;}
#tb8 th {background-color: #78f0a0;}
#tb9 th {background-color: #78f0c8;}
#tb10 th {background-color: #78f0f0;}
#tb11 th {background-color: #78c8f0;}
#tb12 th {background-color: #78a0f0;}
#tb13 th {background-color: #7878f0;}
#tb14 th {background-color: #a078f0;}
#tb15 th {background-color: #c878f0;}
#tb16 th {background-color: #f078f0;}
#tb17 th {background-color: #f078c8;}
#tb18 th {background-color: #f078a0;}
#tb99 th {background-color: #808080;}
color:#5B5B5B;
.testRect {outline: 2px dotted lightblue;}
background-color: skyblue;
body {background-color: #161b22; color: #b3b3b3; font-size: 12px;}
code {background: #303030 !important; border: 1px solid rgba(255, 255, 255, .1);
.good {color: #8cdca7;} /* test7 */
.bad {color: #dc8c8c;}
hr {color: #dcdc8c}
<td class="mono spaces" id="legend" style="text-align: left; vertical-align: top; color: #b3b3b3; font-size: 11px"></td>
.s1 {background-color: #161b22; color: #dc8c8c;}
.btnfirst {background-color: #161b22;
hr {color: #dcdc8c}
<td class="mono spaces" id="legend" style="text-align: left; vertical-align: top; color: #b3b3b3; font-size: 11px"></td>
hr {color: #8cdcc1}
<canvas id="cnvBig" width="180" height="180" style="border:5px solid white;"></canvas> &nbsp
<canvas id="cnvCtrl" width="20" height="20" style="border:1px solid white;"></canvas>
<canvas id="cnvBig2" width="180" height="180" style="border:5px solid white;"></canvas> &nbsp
<canvas id="cnvGet" width="20" height="20" style="border:1px solid white;"></canvas>
<canvas id="cnvGet2" width="20" height="20" style="border:1px solid white;" src=""></canvas>
<image id="cnvURL" width="20" height="20" style="border:1px solid white;" src=""></image>
<image id="cnvBlob" width="20" height="20" style="border:1px solid white;" src=""></image>
hr {color: #8cdcc1}
<br><span class="spaces" style="color: #b3b3b3;" id="totals"></span>
<br><span class="spaces" style="color: #b3b3b3;" id="results"></span>
ctx.fillStyle = "rgba(" + (x*y) +","+ (x*16) +","+ (y*16) +",255)"
hr {color: #8ca7dc}
<span class="mono spaces" style="color: #b3b3b3;" id="statstitle"></span>
<span style="color: #b3b3b3;">click counts to log: ; single line ; multi-line</span>
<span class="mono spaces" style="color: #b3b3b3;" id="stats"></span>
hr {color: #dcc18c}
.a{border-width: 1px; border-style: solid; border-color: black; border-image: linear-gradient(white,black);}
<div id="test95a" style="width: min-content; hyphens: auto; border: 1px solid red">2020-1</div>
<div id="test95b" style="width: min-content; hyphens: auto; border: 1px solid red">2020-12020-1</div>
<td><canvas id="control1" width="16" height="16" style="border:1px solid white;"></canvas></td>
<canvas id="control2" width="16" height="16" style="border:1px solid white;"></canvas>
<td class="mono spaces" id="legend" style="text-align: left; vertical-align: top; color: #b3b3b3; font-size: 11px;"></td>
hr {color: #dcc18c}
#tb4 th {background-color: #f0c878;}
```

</details>
